package org.tyler.model.food;

/**
 * Public view of a saved food record with its database {@code id} and {@link Food}.
 *
 * <p>The frontend uses the ID to delete a specific entry
 * without comparing the full {@link Food} value or rewriting all records.
 *
 * <p>The internal {@code createdAt} timestamp belongs to {@link FoodRecord};
 * this view exposes only the ID and food data needed by the UI.
 *
 * @param id   database ID generated by SQLite
 * @param food parsed food data
 */
public record FoodEntry(
        long id,
        Food food) {
}
