package org.tyler.model.food;

import java.time.LocalDateTime;

/**
 * Complete database row for a saved food record.
 *
 * <p>Extends the data represented by {@link Food} with a database {@code id}
 * and a {@code createdAt} timestamp so individual entries can be deleted by ID
 * without comparing full food values or rewriting the table.
 *
 * @param id        database ID generated by SQLite
 * @param food      parsed food data
 * @param createdAt creation timestamp
 */
public record FoodRecord(
        long id,
        Food food,
        LocalDateTime createdAt) {
}